apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-ui
  namespace: vivek
spec:
  selector:
    matchLabels:
      app: axion-ui
  template:
    metadata:
      labels:
        app: axion-ui
    spec:
      containers:
      - name: axion-ui
        image: acr22.azurecr.io/vivek-axion-ui:v6
        ports:
        - containerPort: 80
