name: Build and Push to ACR
on: workflow_dispatch
permissions: 
  id-token: write
  contents: write
env:
  IMAGE_NAME: vivek-axion-ui
  VERSION: v${{github.run_number}}
  CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ACR_SERVER: ${{secrets.ACR_NAME}}
jobs:
  Build-and-push:
    name: build the image and push to the acr
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6.1.0

      - name: Azure Login
        uses: Azure/login@v3
        with:
          client-id: ${{env.CLIENT_ID}}
          tenant-id: ${{env.TENANT_ID}}
          subscription-id: ${{env.SUBSCRIPTION_ID}}

      - name: Login ACR
        run: az acr login --name ${{env.ACR_SERVER}}
